name: Trigger auto deployment for myapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/myapp-AutoDeployTrigger-acbbf281-03a0-4593-b093-6f3aec14fb35.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.MYAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.MYAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tadrianonet/nodeazcontainerapps:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n myapp -g medium --server docker.io --username  ${{ secrets.MYAPP_REGISTRY_USERNAME }} --password ${{ secrets.MYAPP_REGISTRY_PASSWORD }}
            az containerapp update -n myapp -g medium --image tadrianonet/nodeazcontainerapps:${{ github.sha }}
